# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 04:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_tool_image_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='image_name',
            new_name='keyword',
        ),
    ]
